-- ENY Community Complaints Seed
-- ~20 realistic complaints, mix of statuses and priorities, all pre-approved

INSERT INTO "complaints" (title, description, category, location, status, priority, "submittedBy", "submittedDate", "resolvedDate", response, "submissionStatus", "createdAt", "updatedAt") VALUES
('Pothole on New Lots Avenue', 'Large pothole near the intersection of New Lots Ave and Van Sinderen Ave. Multiple vehicles have been damaged. Needs immediate repair.', 'Infrastructure', 'New Lots Ave & Van Sinderen Ave, Brooklyn 11207', 'RESOLVED', 'HIGH', 'Marcus Johnson', '2026-01-15', '2026-02-10', 'DOT has completed the repair. Thank you for reporting.', 'APPROVED', NOW(), NOW()),
('Illegal Dumping on Alabama Ave', 'Repeated illegal dumping of furniture and construction debris on the vacant lot at 520 Alabama Ave. Attracts rodents and is an eyesore.', 'Sanitation', '520 Alabama Ave, Brooklyn 11207', 'IN_PROGRESS', 'HIGH', 'Denise Williams', '2026-02-20', NULL, 'Sanitation department has been notified and will schedule a cleanup.', 'APPROVED', NOW(), NOW()),
('Broken Streetlight on Livonia Ave', 'The streetlight outside 789 Livonia Ave has been out for over three weeks. Very dark and unsafe at night.', 'Infrastructure', '789 Livonia Ave, Brooklyn 11207', 'PENDING', 'MEDIUM', 'Robert Chen', '2026-03-01', NULL, NULL, 'APPROVED', NOW(), NOW()),
('Noise from Late-Night Construction', 'Construction crew working past 10 PM on the new development at Pitkin Ave and Pennsylvania Ave. Violating noise ordinances multiple nights per week.', 'Noise', '2600 Pitkin Ave, Brooklyn 11208', 'RESOLVED', 'MEDIUM', 'Angela Torres', '2026-01-28', '2026-02-15', 'DOB inspected the site and issued a violation. Construction now stops at 6 PM.', 'APPROVED', NOW(), NOW()),
('Overflowing Trash Bins at Linden Park', 'Public trash bins in Linden Park have been overflowing for days. Garbage is scattered around the playground area.', 'Sanitation', 'Linden Park, Linden Blvd & Vermont St, Brooklyn', 'IN_PROGRESS', 'MEDIUM', 'Patricia Moore', '2026-03-10', NULL, NULL, 'APPROVED', NOW(), NOW()),
('Abandoned Vehicle on Sutter Ave', 'A stripped and abandoned vehicle has been parked at 405 Sutter Ave for over a month. License plates removed. Possible safety hazard.', 'Safety', '405 Sutter Ave, Brooklyn 11207', 'PENDING', 'LOW', 'James Brown', '2026-03-05', NULL, NULL, 'APPROVED', NOW(), NOW()),
('Speeding on Linden Blvd', 'Drivers consistently speeding through the school zone on Linden Blvd near Schenck Ave during school hours. Children at risk.', 'Traffic', 'Linden Blvd & Schenck Ave, Brooklyn 11207', 'IN_PROGRESS', 'HIGH', 'Sandra Mitchell', '2026-02-14', NULL, 'Request submitted to DOT for speed camera installation.', 'APPROVED', NOW(), NOW()),
('Rats in Vacant Lot', 'Large rat infestation in the vacant lot on the corner of Liberty Ave and Shepherd Ave. Residents have seen rats entering nearby homes.', 'Sanitation', 'Liberty Ave & Shepherd Ave, Brooklyn 11208', 'PENDING', 'HIGH', 'David Okafor', '2026-03-12', NULL, NULL, 'APPROVED', NOW(), NOW()),
('Cracked Sidewalk Hazard', 'Severely cracked and raised sidewalk in front of 1150 Liberty Ave creating a trip hazard. An elderly neighbor fell last week.', 'Infrastructure', '1150 Liberty Ave, Brooklyn 11208', 'RESOLVED', 'MEDIUM', 'Maria Gonzalez', '2025-12-10', '2026-01-20', 'Sidewalk repair completed by DOT.', 'APPROVED', NOW(), NOW()),
('Graffiti on Community Center', 'Extensive graffiti vandalism on the exterior walls of the community center at 234 Glenmore Ave. Appeared overnight.', 'Safety', '234 Glenmore Ave, Brooklyn 11207', 'PENDING', 'LOW', 'Kevin Wright', '2026-03-18', NULL, NULL, 'APPROVED', NOW(), NOW()),
('Fire Hydrant Leaking on Sutter Ave', 'The fire hydrant in front of 380 Sutter Ave has been leaking continuously for two weeks. Water is pooling on the sidewalk and street.', 'Infrastructure', '380 Sutter Ave, Brooklyn 11207', 'IN_PROGRESS', 'MEDIUM', 'Lisa Henderson', '2026-03-02', NULL, 'DEP has been notified and scheduled a repair crew.', 'APPROVED', NOW(), NOW()),
('Double-Parked Trucks Blocking Bus Stop', 'Delivery trucks regularly double-park at the B15 bus stop on New Lots Ave near Pennsylvania Ave, forcing riders into traffic.', 'Traffic', 'New Lots Ave & Pennsylvania Ave, Brooklyn 11207', 'PENDING', 'HIGH', 'Tyrone Jackson', '2026-03-20', NULL, NULL, 'APPROVED', NOW(), NOW()),
('Playground Equipment Broken at Schenck Park', 'Two swings and the slide at Schenck Playground are broken. Sharp exposed metal edges are a danger to children.', 'Parks & Recreation', 'Schenck Ave & Livonia Ave, Brooklyn 11207', 'IN_PROGRESS', 'HIGH', 'Fatima Ali', '2026-02-28', NULL, 'NYC Parks has ordered replacement parts. Temporary barriers installed.', 'APPROVED', NOW(), NOW()),
('Loud Music from Auto Shop Every Night', 'The auto repair shop at 715 Van Sinderen Ave blasts music until 2 AM on weeknights. Multiple neighbors affected.', 'Noise', '715 Van Sinderen Ave, Brooklyn 11207', 'RESOLVED', 'MEDIUM', 'Carmen Reyes', '2026-01-20', '2026-02-05', 'NYPD Community Affairs spoke with the business owner. Issue resolved.', 'APPROVED', NOW(), NOW()),
('Standing Water Breeding Mosquitoes', 'Large puddle of standing water in the vacant lot at Hegeman Ave and Miller Ave. Mosquitoes are swarming in warmer weather.', 'Sanitation', 'Hegeman Ave & Miller Ave, Brooklyn 11207', 'PENDING', 'MEDIUM', 'Rosa Martinez', '2026-03-15', NULL, NULL, 'APPROVED', NOW(), NOW()),
('Missing Stop Sign at Intersection', 'The stop sign at the corner of Shepherd Ave and Sutter Ave was knocked down by a vehicle and never replaced. Near-misses daily.', 'Traffic', 'Shepherd Ave & Sutter Ave, Brooklyn 11208', 'RESOLVED', 'HIGH', 'Anthony Brooks', '2026-02-01', '2026-02-20', 'DOT installed a new stop sign on 2/19.', 'APPROVED', NOW(), NOW()),
('Overflowing Catch Basin on Pitkin Ave', 'The storm drain at 2500 Pitkin Ave is completely clogged. Every rain causes street flooding that blocks the crosswalk.', 'Infrastructure', '2500 Pitkin Ave, Brooklyn 11208', 'IN_PROGRESS', 'MEDIUM', 'Diane Foster', '2026-03-08', NULL, NULL, 'APPROVED', NOW(), NOW()),
('Homeless Encampment Under Bridge', 'Growing encampment under the LIRR overpass at Atlantic Ave and Van Sinderen Ave. Residents need services and outreach.', 'Safety', 'Atlantic Ave & Van Sinderen Ave, Brooklyn 11207', 'IN_PROGRESS', 'HIGH', 'William Clark', '2026-02-10', NULL, 'DHS outreach team has visited the site and is connecting individuals with shelter services.', 'APPROVED', NOW(), NOW()),
('Faded Crosswalk at School Zone', 'The crosswalk markings in front of PS 7 on Livonia Ave are completely faded. Children cross here daily and drivers cannot see the markings.', 'Roads & Sidewalks', '858 Livonia Ave, Brooklyn 11207', 'PENDING', 'HIGH', 'Michelle Thompson', '2026-03-22', NULL, NULL, 'APPROVED', NOW(), NOW());
