-- ENY Community Events Seed
-- ~8 upcoming 2026 events, all pre-approved

INSERT INTO "events" (title, category, description, date, time, location, organizer, attendees, "maxAttendees", "submissionStatus", "createdAt", "updatedAt") VALUES
('Spring Community Clean-Up', 'Community Service', 'Join neighbors for our annual spring clean-up of local parks and streets in East New York. Supplies provided.', '2026-04-11', '09:00 AM - 1:00 PM', 'Linden Park, Linden Blvd & Vermont St, Brooklyn', 'CB5 ENY', 12, 75, 'APPROVED', NOW(), NOW()),
('Youth Job Fair 2026', 'Education', 'Career expo for young adults ages 16-24 with local employers, resume workshops, and on-the-spot interviews.', '2026-04-25', '10:00 AM - 3:00 PM', 'East New York Family Academy, 1420 Linden Blvd', 'East New York Urban Youth Corps', 30, 200, 'APPROVED', NOW(), NOW()),
('Juneteenth Cultural Celebration', 'Cultural', 'Live music, food vendors, spoken word, and a history walk celebrating freedom and community in ENY.', '2026-06-19', '12:00 PM - 6:00 PM', 'Schenck Playground, Livonia Ave & Schenck Ave', 'CB5 ENY & Grow Brownsville', 0, 500, 'APPROVED', NOW(), NOW()),
('Summer Reading Kick-Off', 'Education', 'Free books, storytime, and sign-ups for the Brooklyn Public Library summer reading challenge. All ages welcome.', '2026-06-27', '11:00 AM - 2:00 PM', 'New Lots Library, 665 New Lots Ave', 'Brooklyn Public Library', 5, 100, 'APPROVED', NOW(), NOW()),
('Back to School Supply Drive', 'Community Service', 'Free backpacks, school supplies, and haircuts for students K-12. First come, first served.', '2026-08-22', '10:00 AM - 2:00 PM', 'Universe City, 234 Glenmore Ave', 'Universe City & CB5 ENY', 0, 300, 'APPROVED', NOW(), NOW()),
('ENY Small Business Saturday', 'Business', 'Shop local and support East New York businesses. Special discounts, live entertainment, and raffle prizes.', '2026-11-28', '10:00 AM - 5:00 PM', 'Pitkin Ave Commercial Corridor', 'Brooklyn Builders Collective', 0, 150, 'APPROVED', NOW(), NOW()),
('Community Board 5 Monthly Meeting', 'Government', 'Open public meeting of Brooklyn Community Board 5. Hear updates, raise concerns, and participate in civic life.', '2026-04-15', '6:00 PM - 8:30 PM', '1285 Decatur St, Brooklyn, NY 11207', 'Brooklyn Community Board 5', 8, 80, 'APPROVED', NOW(), NOW()),
('Outdoor Movie Night: Encanto', 'Entertainment', 'Free outdoor screening of Encanto with popcorn and drinks. Bring a blanket or chair!', '2026-07-18', '8:00 PM - 10:30 PM', 'Highland Park, Jamaica Ave & Elton St', 'NYC Parks & CB5 ENY', 0, 250, 'APPROVED', NOW(), NOW());
