-- ENY Community Events Seed
-- ~20 upcoming 2026 events, all pre-approved

INSERT INTO "events" (title, category, description, date, time, location, organizer, attendees, "maxAttendees", "submissionStatus", "createdAt", "updatedAt") VALUES
('Spring Community Clean-Up', 'Community Service', 'Join neighbors for our annual spring clean-up of local parks and streets in East New York. Supplies provided.', '2026-04-11', '09:00 AM - 1:00 PM', 'Linden Park, Linden Blvd & Vermont St, Brooklyn', 'CB5 ENY', 12, 75, 'APPROVED', NOW(), NOW()),
('Youth Job Fair 2026', 'Education', 'Career expo for young adults ages 16-24 with local employers, resume workshops, and on-the-spot interviews.', '2026-04-25', '10:00 AM - 3:00 PM', 'East New York Family Academy, 1420 Linden Blvd', 'East New York Urban Youth Corps', 30, 200, 'APPROVED', NOW(), NOW()),
('Juneteenth Cultural Celebration', 'Cultural', 'Live music, food vendors, spoken word, and a history walk celebrating freedom and community in ENY.', '2026-06-19', '12:00 PM - 6:00 PM', 'Schenck Playground, Livonia Ave & Schenck Ave', 'CB5 ENY & Grow Brownsville', 0, 500, 'APPROVED', NOW(), NOW()),
('Summer Reading Kick-Off', 'Education', 'Free books, storytime, and sign-ups for the Brooklyn Public Library summer reading challenge. All ages welcome.', '2026-06-27', '11:00 AM - 2:00 PM', 'New Lots Library, 665 New Lots Ave', 'Brooklyn Public Library', 5, 100, 'APPROVED', NOW(), NOW()),
('Back to School Supply Drive', 'Community Service', 'Free backpacks, school supplies, and haircuts for students K-12. First come, first served.', '2026-08-22', '10:00 AM - 2:00 PM', 'Universe City, 234 Glenmore Ave', 'Universe City & CB5 ENY', 0, 300, 'APPROVED', NOW(), NOW()),
('ENY Small Business Saturday', 'Business', 'Shop local and support East New York businesses. Special discounts, live entertainment, and raffle prizes.', '2026-11-28', '10:00 AM - 5:00 PM', 'Pitkin Ave Commercial Corridor', 'Brooklyn Builders Collective', 0, 150, 'APPROVED', NOW(), NOW()),
('Community Board 5 Monthly Meeting', 'Government', 'Open public meeting of Brooklyn Community Board 5. Hear updates, raise concerns, and participate in civic life.', '2026-04-15', '6:00 PM - 8:30 PM', '1285 Decatur St, Brooklyn, NY 11207', 'Brooklyn Community Board 5', 8, 80, 'APPROVED', NOW(), NOW()),
('Outdoor Movie Night: Encanto', 'Entertainment', 'Free outdoor screening of Encanto with popcorn and drinks. Bring a blanket or chair!', '2026-07-18', '8:00 PM - 10:30 PM', 'Highland Park, Jamaica Ave & Elton St', 'NYC Parks & CB5 ENY', 0, 250, 'APPROVED', NOW(), NOW()),
('Free Tax Prep Clinic', 'Community Service', 'IRS-certified volunteers help you file your taxes for free. Bring W-2s, photo ID, and Social Security cards. Walk-ins welcome.', '2026-04-05', '10:00 AM - 4:00 PM', 'New Lots Library, 665 New Lots Ave', 'NYC Free Tax Prep', 15, 60, 'APPROVED', NOW(), NOW()),
('ENY Youth Basketball Tournament', 'Sports & Recreation', 'Annual 3-on-3 basketball tournament for ages 12-18. Trophies, free food, and music. Register your team by April 1st.', '2026-04-18', '10:00 AM - 5:00 PM', 'Linden Park Basketball Courts, Brooklyn', 'East New York Urban Youth Corps', 40, 120, 'APPROVED', NOW(), NOW()),
('Senior Wellness Fair', 'Community Service', 'Free health screenings, blood pressure checks, flu shots, and wellness workshops for seniors 60+. Light refreshments provided.', '2026-05-03', '9:00 AM - 1:00 PM', 'HANAC Senior Center, 27 Schenck Ave, Brooklyn', 'CB5 ENY & NYC Health', 10, 80, 'APPROVED', NOW(), NOW()),
('Mothers Day Brunch & Celebration', 'Cultural', 'Honor the mothers of East New York with a community brunch, live performances, and raffle prizes. RSVP required.', '2026-05-10', '11:00 AM - 2:00 PM', 'Universe City, 234 Glenmore Ave', 'Grow Brownsville', 0, 100, 'APPROVED', NOW(), NOW()),
('Community Board 5 Public Hearing: Rezoning', 'Government', 'Public hearing on the proposed East New York rezoning plan. Share your opinions and hear from city planners.', '2026-05-20', '6:30 PM - 9:00 PM', '1285 Decatur St, Brooklyn, NY 11207', 'Brooklyn Community Board 5', 22, 120, 'APPROVED', NOW(), NOW()),
('ENY Summer Kickoff Block Party', 'Entertainment', 'DJ, bounce house, face painting, free food, and community resource tables. Fun for the whole family!', '2026-06-06', '12:00 PM - 6:00 PM', 'New Lots Ave between Barbey St & Jerome St', 'CB5 ENY & Local Merchants', 0, 400, 'APPROVED', NOW(), NOW()),
('Coding & Robotics Camp Info Session', 'Education', 'Learn about free summer coding and robotics camps for youth ages 10-17. Meet instructors and see demos.', '2026-05-30', '2:00 PM - 4:00 PM', 'East New York Family Academy, 1420 Linden Blvd', 'Per Scholas & CB5 ENY', 8, 50, 'APPROVED', NOW(), NOW()),
('Community Garden Planting Day', 'Community Service', 'Help plant vegetables and flowers at the ENY community garden. Seeds, soil, and tools provided. All ages.', '2026-04-26', '9:00 AM - 12:00 PM', 'ENY Community Garden, 504 New Jersey Ave, Brooklyn', 'GreenThumb NYC', 6, 40, 'APPROVED', NOW(), NOW()),
('Know Your Rights Workshop', 'Education', 'Free legal workshop covering tenants rights, immigration basics, and how to interact with law enforcement. Spanish translation available.', '2026-05-16', '10:00 AM - 12:30 PM', 'New Lots Library, 665 New Lots Ave', 'Brooklyn Legal Services', 20, 75, 'APPROVED', NOW(), NOW()),
('ENY Bike Ride: Explore the Neighborhood', 'Sports & Recreation', 'Guided group bike ride through East New York landmarks. Helmets required. Bikes available to borrow (first come, first served).', '2026-06-14', '9:00 AM - 11:30 AM', 'Highland Park, Jamaica Ave & Elton St', 'Transportation Alternatives', 0, 35, 'APPROVED', NOW(), NOW()),
('4th of July Community Cookout', 'Entertainment', 'Annual Independence Day cookout with grilled food, music, games, and fireworks viewing. Free and open to all ENY residents.', '2026-07-04', '3:00 PM - 10:00 PM', 'Linden Park, Linden Blvd & Vermont St, Brooklyn', 'CB5 ENY', 0, 500, 'APPROVED', NOW(), NOW()),
('Back to School Health Screening', 'Community Service', 'Free physicals, vision tests, and dental screenings for students heading back to school. Bring immunization records.', '2026-08-15', '9:00 AM - 3:00 PM', 'Brookdale Hospital Community Room, 1 Brookdale Plaza', 'Brookdale Hospital & CB5 ENY', 0, 150, 'APPROVED', NOW(), NOW());
