-- ENY Community Complaints Seed
-- ~10 realistic complaints, mix of statuses and priorities, all pre-approved

INSERT INTO "complaints" (title, description, category, location, status, priority, "submittedBy", "submittedDate", "resolvedDate", response, "submissionStatus", "createdAt", "updatedAt") VALUES
('Pothole on New Lots Avenue', 'Large pothole near the intersection of New Lots Ave and Van Sinderen Ave. Multiple vehicles have been damaged. Needs immediate repair.', 'Infrastructure', 'New Lots Ave & Van Sinderen Ave, Brooklyn 11207', 'RESOLVED', 'HIGH', 'Marcus Johnson', '2026-01-15', '2026-02-10', 'DOT has completed the repair. Thank you for reporting.', 'APPROVED', NOW(), NOW()),
('Illegal Dumping on Alabama Ave', 'Repeated illegal dumping of furniture and construction debris on the vacant lot at 520 Alabama Ave. Attracts rodents and is an eyesore.', 'Sanitation', '520 Alabama Ave, Brooklyn 11207', 'IN_PROGRESS', 'HIGH', 'Denise Williams', '2026-02-20', NULL, 'Sanitation department has been notified and will schedule a cleanup.', 'APPROVED', NOW(), NOW()),
('Broken Streetlight on Livonia Ave', 'The streetlight outside 789 Livonia Ave has been out for over three weeks. Very dark and unsafe at night.', 'Infrastructure', '789 Livonia Ave, Brooklyn 11207', 'PENDING', 'MEDIUM', 'Robert Chen', '2026-03-01', NULL, NULL, 'APPROVED', NOW(), NOW()),
('Noise from Late-Night Construction', 'Construction crew working past 10 PM on the new development at Pitkin Ave and Pennsylvania Ave. Violating noise ordinances multiple nights per week.', 'Noise', '2600 Pitkin Ave, Brooklyn 11208', 'RESOLVED', 'MEDIUM', 'Angela Torres', '2026-01-28', '2026-02-15', 'DOB inspected the site and issued a violation. Construction now stops at 6 PM.', 'APPROVED', NOW(), NOW()),
('Overflowing Trash Bins at Linden Park', 'Public trash bins in Linden Park have been overflowing for days. Garbage is scattered around the playground area.', 'Sanitation', 'Linden Park, Linden Blvd & Vermont St, Brooklyn', 'IN_PROGRESS', 'MEDIUM', 'Patricia Moore', '2026-03-10', NULL, NULL, 'APPROVED', NOW(), NOW()),
('Abandoned Vehicle on Sutter Ave', 'A stripped and abandoned vehicle has been parked at 405 Sutter Ave for over a month. License plates removed. Possible safety hazard.', 'Safety', '405 Sutter Ave, Brooklyn 11207', 'PENDING', 'LOW', 'James Brown', '2026-03-05', NULL, NULL, 'APPROVED', NOW(), NOW()),
('Speeding on Linden Blvd', 'Drivers consistently speeding through the school zone on Linden Blvd near Schenck Ave during school hours. Children at risk.', 'Traffic', 'Linden Blvd & Schenck Ave, Brooklyn 11207', 'IN_PROGRESS', 'HIGH', 'Sandra Mitchell', '2026-02-14', NULL, 'Request submitted to DOT for speed camera installation.', 'APPROVED', NOW(), NOW()),
('Rats in Vacant Lot', 'Large rat infestation in the vacant lot on the corner of Liberty Ave and Shepherd Ave. Residents have seen rats entering nearby homes.', 'Sanitation', 'Liberty Ave & Shepherd Ave, Brooklyn 11208', 'PENDING', 'HIGH', 'David Okafor', '2026-03-12', NULL, NULL, 'APPROVED', NOW(), NOW()),
('Cracked Sidewalk Hazard', 'Severely cracked and raised sidewalk in front of 1150 Liberty Ave creating a trip hazard. An elderly neighbor fell last week.', 'Infrastructure', '1150 Liberty Ave, Brooklyn 11208', 'RESOLVED', 'MEDIUM', 'Maria Gonzalez', '2025-12-10', '2026-01-20', 'Sidewalk repair completed by DOT.', 'APPROVED', NOW(), NOW()),
('Graffiti on Community Center', 'Extensive graffiti vandalism on the exterior walls of the community center at 234 Glenmore Ave. Appeared overnight.', 'Safety', '234 Glenmore Ave, Brooklyn 11207', 'PENDING', 'LOW', 'Kevin Wright', '2026-03-18', NULL, NULL, 'APPROVED', NOW(), NOW());
